name: splathon_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  qr_flutter: ^2.0.0+51
  cached_network_image: ^0.7.0
  # workaround fix https://github.com/facundomedica/fast_qr_reader_view/issues/32#issuecomment-471146441
  # 0.1.5だとandroid.supportに依存してしまっているが、masterでは修正されているので。
  # 次のversionがリリースされたら version 指定に戻すとかするべき
  fast_qr_reader_view:
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git
  firebase_messaging: ^4.0.0+4
  shared_preferences: ^0.5.2
  auto_size_text: ^1.1.2
  event_bus: ^1.1.0
  url_launcher: ^5.0.2
  openapi:
    path: client/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/images/icon-splathon-app.png"
  # Need run follow command to update app icons
  # $flutter pub pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  
  assets:
   - assets/images/icon_notification.png
   - assets/images/icon_result.png
   - assets/images/icon_ranking.png
   - assets/images/icon_reception.png
   - assets/images/crown1.png
   - assets/images/crown2.png
   - assets/images/crown3.png
   - assets/images/arrowRight.png
   - assets/images/goldInc.png
   - assets/images/silverInc.png
   - assets/images/arrowUp.png
   - assets/images/arrowDownW.png
   - assets/images/reloadIcon.png
   - assets/images/girl.png

  fonts:
    - family: Splatfont
      fonts:
        - asset: assets/fonts/Splatfont.ttf