// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCdFIVhEc8O0XN7TZpAYk3buyFs1oqDxo',
    appId: '1:253080974091:web:83d8dff71fe809ae07e80e',
    messagingSenderId: '253080974091',
    projectId: 'splathon10-apps',
    authDomain: 'splathon10-apps.firebaseapp.com',
    databaseURL: 'https://splathon10-apps.firebaseio.com',
    storageBucket: 'splathon10-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3qzGMGqIxrqflqBS1d_7dmcLO71PWE8',
    appId: '1:253080974091:android:aa0df6e938748f0707e80e',
    messagingSenderId: '253080974091',
    projectId: 'splathon10-apps',
    databaseURL: 'https://splathon10-apps.firebaseio.com',
    storageBucket: 'splathon10-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNem-XmVEKb9SQbrY9z-iYR5sS02Uo_o',
    appId: '1:253080974091:ios:acc050cbfdf2909507e80e',
    messagingSenderId: '253080974091',
    projectId: 'splathon10-apps',
    databaseURL: 'https://splathon10-apps.firebaseio.com',
    storageBucket: 'splathon10-apps.appspot.com',
    iosClientId: '253080974091-csdmn1f0867cia555jha5pchrbrckt59.apps.googleusercontent.com',
    iosBundleId: 'com.example.splathonClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNem-XmVEKb9SQbrY9z-iYR5sS02Uo_o',
    appId: '1:253080974091:ios:acc050cbfdf2909507e80e',
    messagingSenderId: '253080974091',
    projectId: 'splathon10-apps',
    databaseURL: 'https://splathon10-apps.firebaseio.com',
    storageBucket: 'splathon10-apps.appspot.com',
    iosClientId: '253080974091-csdmn1f0867cia555jha5pchrbrckt59.apps.googleusercontent.com',
    iosBundleId: 'com.example.splathonClient',
  );
}
